### ISSUE TITLE
Problem of running uldaq python example

### ISSUE THREAD

**Issue by clappertown** [mccdaq/uldaq#42]
I have following problem running uldaq python example on my M1 MacOS system:

MacBook-Pro-M1:examples local$ ./a_in.py 
Traceback (most recent call last):
  File "./a_in.py", line 30, in <module>
    from uldaq import (get_daq_device_inventory, DaqDevice, InterfaceType,
  File "/usr/local/lib/python2.7/site-packages/uldaq/__init__.py", line 1, in <module>
    from .daq_device_discovery import get_daq_device_inventory
  File "/usr/local/lib/python2.7/site-packages/uldaq/daq_device_discovery.py", line 9, in <module>
    from .ul_exception import ULException
  File "/usr/local/lib/python2.7/site-packages/uldaq/ul_exception.py", line 6, in <module>
    from .ul_c_interface import lib
  File "/usr/local/lib/python2.7/site-packages/uldaq/ul_c_interface.py", line 15, in <module>
    lib = CDLL('libuldaq.dylib')
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libuldaq.dylib, 0x0006): tried: 'libuldaq.dylib' (no such file), '/usr/local/lib/libuldaq.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/lib/libuldaq.dylib' (no such file), '/Users/local/Downloads/libuldaq-1.2.1/uldaq-1.2.3/examples/libuldaq.dylib' (no such file)

**Comment by sbazaz** [comment]
It seems you have the Intel (x86) version of python installed on your M1 system. Uninstall  the current version of python from your system, go to  [python.org](https://www.python.org/downloads/macos/) and make sure to download and install the universal version of  python for macOS 64-bit, not the Intel only version. The package is called macOS 64-bit universal2 installer.
